pipeline
{
  agent any

  tools
  {
    maven 'MAVEN3.9.9'
  }
  
  stages
  {
    stage('checkout code from github repo')
    {
      steps
      {
        sh 'git clone https://github.com/RavitejaAdepudi/vamsi.git'
      }
    }
    stage('building the code')
    {
      steps
      {
        sh 'mvn -f /var/lib/jenkins/workspace/3rd/vamsi/mavewebappdemo/pom.xml install'
      }
    }
        stage('deploying the code')
    {
      steps
      {
         sh ' cp -r /var/lib/jenkins/workspace/3rd/vamsi/mavewebappdemo/target/*.war /opt/apache-tomcat-9.0.102/webapps '
      }
    }
  }
}
